(package "ace-link-dashboard"
         "0.1.0"
         "Ace link for emacs-dashboard")

(website-url "https://github.com/jcs-PR/ace-link-dashboard")
(keywords "tools")

(package-file "ace-link-dashboard.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "avy")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
