(package "ace-link-dashboard"
         "0.1.0"
         "Ace link for dashboard")

(website-url "https://github.com/emacs-dashboard/ace-link-dashboard")
(keywords "tools")

(package-file "ace-link-dashboard.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.1")
(depends-on "avy")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
